{% set name = "imio" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/imio-{{ version }}.tar.gz
  sha256: d200f918b86dac17ec00b563a8eb7abc936f6d3d10dce0cef1b0296d5e74bf65

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - brainglobe-utils
    - natsort
    - nibabel
    - numpy
    - psutil
    - pynrrd
    - python >={{ python_min }}
    - scikit-image
    - scipy
    - tifffile
    - tqdm
    - pyarrow

test:
  imports:
    - imio
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/brainglobe/imio
  summary: Loading and saving of image data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
