{% set name = "imio" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/imio-{{ version }}.tar.gz
  sha256: ee183492814c15b3b4b3be484f783712062c83f107ae53d74a5a4db0ea3381a7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - imlib
    - natsort
    - nibabel
    - numpy
    - psutil
    - pynrrd
    - python >=3.7
    - scikit-image
    - slurmio >=0.0.5
    - tifffile
    - tqdm

test:
  imports:
    - imio
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brainglobe/imio
  summary: Loading and saving of image data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
